document.writeln("        <div class=\"b-block\">");
document.writeln("            <div class=\"b-card\" style=\"padding: 10px; text-align: center;\">");
document.writeln("                <p class=\"t-bold\">");
document.writeln("                    还给我六个币");
document.writeln("                    <a href =\"https://github.com/HuanGeiWoLiuGeBi\" target=\"_blank\">Github</a>");
document.writeln("                    <a href=\"https://space.bilibili.com/590621781\" target=\"_blank\">Bilibili</a>");
document.writeln("                    Return_761");
document.writeln("                    <a href=\"https://github.com/Return761\" target=\"_blank\">Github</a>");
document.writeln("                    <a href=\"https://space.bilibili.com/1986062921\" target=\"_blank\">Bilibili</a>");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("            <p class=\"s-5\"></p>");
document.writeln("            <div class=\"b-card\" style=\"padding: 10px; text-align: center;\">");
document.writeln("                <a href=\"../index.html\">返回首页</a>");
document.writeln("                <a href=\"#\" onclick=\"javascript:history.back(-1);\">返回上页</a>");
document.writeln("                <a href=\"A-3.html\">关于本站</a>");
document.writeln("                <a href=\"B-1.html\">所有文章</a>");
document.writeln("                <a href=\"A-4.html\">网页映射</a>");
document.writeln("            </div>");
document.writeln("        </div>");