document.writeln("        <div class=\"b-block\">");
document.writeln("            <div class=\"b-card\" style=\"padding: 10px; text-align: center;\">");
document.writeln("                <p class=\"t-footer\">");
document.writeln("                    还给我六个币");
document.writeln("                    <a href =\"https://github.com/HuanGeiWoLiuGeBi\" target=\"_blank\" class=\"t-footer\">Github</a>");
document.writeln("                    <a href=\"https://space.bilibili.com/590621781\" target=\"_blank\" class=\"t-footer\">Bilibili</a>");
document.writeln("                    Return_761");
document.writeln("                    <a href=\"https://github.com/Return761\" target=\"_blank\" class=\"t-footer\">Github</a>");
document.writeln("                    <a href=\"https://space.bilibili.com/1986062921\" target=\"_blank\" class=\"t-footer\">Bilibili</a>");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("            <p class=\"s-5\"></p>");
document.writeln("            <div class=\"b-card\" style=\"padding: 10px; text-align: center;\">");
document.writeln("                <p class=\"t-footer\">");
document.writeln("                    <a href=\"A-1.html\" class=\"t-footer\">返回首页</a>");
document.writeln("                    <a href=\"#\" onclick=\"javascript:history.back(-1);\" class=\"t-footer\">返回上页</a>");
document.writeln("                    <a href=\"A-2.html\" class=\"t-footer\">关于本站</a>");
document.writeln("                    <a href=\"B-1.html\" class=\"t-footer\">所有文章</a>");
document.writeln("                    <a href=\"A-3.html\" class=\"t-footer\">网页映射</a>");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("        </div>");