document.write("        <div class=\"navbar-block\">");
document.write("            <img class=\"navbar-image\" src=\"..\/images\/navbar-icon.png\">");
document.write("            <p class=\"navbar-title\">SNR团队官方网站<\/p>");
document.write("            <a href=\"..\/index.html\" class=\"navbar-homepage\">首页<\/a>");
document.write("            <a href=\"#\" class=\"navbar-homepage\" onclick=\"javascript:history.back(-1);\">上页<\/a>");
document.write("			<a href=\"https:\/\/github.com\/HuanGeiWoLiuGeBi\" class=\"navbar-website\" target=\"_blank\">Github<\/a>");
document.write("			<a href=\"https:\/\/space.bilibili.com\/590621781\" class=\"navbar-website\" target=\"_blank\">Bilibili<\/a>");
document.write("			<p class=\"navbar-websitet\">还给我六个币<\/p>");
document.write("			<a href=\"https:\/\/github.com\/Return761\" class=\"navbar-website\" target=\"_blank\">Github<\/a>");
document.write("			<a href=\"https:\/\/space.bilibili.com\/1986062921\" class=\"navbar-website\" target=\"_blank\">Bilibili<\/a>");
document.write("			<p class=\"navbar-websitet\">Return_761<\/p>");
document.write("        <\/div>");
document.write("        <p class=\"article-space70px\"><\/p>");