document.write("        <div class=\"b-navbar\">");
document.write("            <img class=\"n-image\" src=\"..\/images\/nicon.png\">");
document.write("            <p class=\"t-navbartitle\">SNR团队官方网站<\/p>");
document.write("            <a href=\"A-1.html\" class=\"t-navbarlink\">首页<\/a>");
document.write("            <a href=\"..\/special\/startpage\/pages\/startpage.html\" class=\"t-navbarlink\">SNR Start[开发中]<\/a>");
document.write("            <a href=\"#\" class=\"t-navbarlink\" onclick=\"javascript:history.back(-1);\">上页<\/a>");
document.write("            <a href=\"A-3.html\" class=\"t-navbarlink\">关于本站<\/a>");
document.write("            <a href=\"B-1.html\" class=\"t-navbarlink\">所有文章<\/a>");
document.write("            <a href=\"A-4.html\" class=\"t-navbarlink\">网页映射<\/a>");
document.write("        <\/div>");
document.write("        <p class=\"s-70\"><\/p>");